### ISSUE TITLE
Thoughts on spec

### ISSUE THREAD

**Issue by osk** [the-colony/rsrf#1]
Interesting work! A few thoughts:

* `seller` should be its own object, e.g. `"seller": { "id": "123", "name": "foo"}` since namespacing with prefixes isn't nice
* `sellerGovernmentID` sounds too specific for the general case, could be addressed via extensions
* `entries.text` sounds too general, `entries.name`?
* Shouldn't entries use UPC?
* Try and keep keys simple, `id` over `receiptID`, `price` over `unitPrice`, `total` over `totalAmount` etc
* `timeZone`, `date` and `time` together in `datetime` that's the full form in UTC, this is explicit (no string concatenations or shenanigans required when parsing to date object in YourFavoriteLanguage) and puts the responsibility on the producer to set default time
* `attachments` should be well defined for the obvious cases and rely on extensions for arbitrary extensions
* `attachment` should not rely on extensions but have a `mimeType` field that explicitly states the file type
* Extensions could be added by prefixing keys on object (`receipt`, `entries`, `attachment` or `seller`) with `_`, see the [JSON Feed spec](https://jsonfeed.org/version/1#attachments)

Rewriting the example:

```
{
  "version": "1",
  "id": "123-456-789",
  "seller": {
    "id": "987-654-321",
    "name": "the Great shop",
    "email": "the.great@shop.com",
    "_govermentId": "091179-4829"
  },
  "datetime": "2017-06-05T18:08:45+00:00",
  "currencyCode": "ISK",
  "total": 844,
  "entries": [
    {
      "name": "Soylent Industries Green no. 3",
      "upc": "5690527101004",
      "quantity": 1,
      "price": 155,
      "total": 155,
      "vat": 0.11
      "_description": "Made with 100% authentic people"
    }
  ],
  "attachements": [
    {
      "name": "receipt.pdf",
      "data": "...",
      "mimeType": "application/pdf"
    }
  ]
}
```

**Comment by hugithordarson** [comment]
Awesome points!

* Regarding the "seller"-prefix, I wholeheartedly agree. Seller info wasn't meant to sprawl like this, but oh well—it did. Changing to an object.
* Regarding `sellerGovernmentID` the rationale for including it is that it's a unique ID usable for matching with a company in case of no shop ID. I kinda sorta agree with you though, but I'm still leaning towards keeping it (at least until we make a decision on whether to allow extensions).
* The reason it's called `entries.text` rather than `entries.name` is that this field will often include free text like "products", "food", "drinks" etc. So it's usually more of a description than an actual product name. Perhaps `description` is the appropriate name? I like it, it's more descriptive than `text`.
* I'd love some input regarding the productCode. The idea is that this should reflect the product's printed barcode—is that always a UPC code? I really need some insight and guidance regarding this aspect since it's outside my field of expertise.
* Regarding the long field names, I understand what you mean, but I'm a fan of verbosity and self documenting code/specs over brevity :). I'll grant you the `id` fields probably don't need the prefixes, but I'd like to keep `unitPrice` and `totalAmount` since they describe the field's contents. Agreed?
* Regarding `date`, `time` and `timeZone` the reason they're kept separate is that the spec needs to be able to accurately reflect real world data where any of those fields might be missing (this is a requirement for us to be able to use this format at Strimillinn).
* I'm very open to defining standardised attachments—that's definitely useful. But perhaps it's something that might be reserved for the next version, so we can push this one out fast?
* `attachment` did indeed initially include a `mimeType` field :). I've just found that mimeType-fields tend to be superfluous, with the entire world constantly converting between extensions and mimeTypes, so it was removed for simplicity's sake and replaced with the requirement for an extension to the filename. But from a Technological Purity Standpoint™ you're absolutely right and it should probably be there. I'll add it again.
* I'l look into the extensions. I'm a bit hesitant though, since I can see it complicate parsing—and it *will* be abused by users to create their own implementations, rather than participate in making the standard better.

Many of your points deserve to be promoted to separate issues so they can be discussed in detail. I'll get on that once I've finished implementing the most obvious changes.

**Comment by hugithordarson** [comment]
On a second thought, I think that to make messages more lightweight, attachments should be references instead of embedded data (i.e. they'd reference URLs). This bypasses the whole extensions vs. mimetypes thing and leaves it up to the server serving the actual file. I've created a separate issue for this, in case anyone wants to discuss it.

**Comment by osk** [comment]
I'll split it up and add some more thoughts during the weekend 🤓

**Comment by hugithordarson** [comment]
Awesome :). Please note I've already split up and resolved several of the issues mentioned.
